export interface Event {
  id: number;
  lat: number;
  lng: number;
  emoji: string;
  title: string;
  image: string;
  category: "social" | "sports" | "wellness" | "entertainment" | "education";
  status: "upcoming" | "ongoing" | "past";
  date: string;
  isPublic: boolean;
  description: string;
  attendees: number;
  isFree: boolean;
  price?: string;
  participantImages: string[];
}

const opt = (url: string) => `${url}?auto=format&fit=crop&q=80&w=800`;

const AVATARS = [
  "https://i.pravatar.cc/150?u=1",
  "https://i.pravatar.cc/150?u=2",
  "https://i.pravatar.cc/150?u=3",
  "https://i.pravatar.cc/150?u=4",
  "https://i.pravatar.cc/150?u=5",
];

export const DEFAULT_EVENTS: Event[] = [
  {
    id: 2,
    lat: 4.8205,
    lng: 7.0355,
    emoji: "⚽",
    title: "5-a-side Football GRA",
    category: "sports",
    image: opt("https://images.unsplash.com/photo-1521412644187-c49fa049e84d"),
    status: "ongoing",
    date: "2026-04-08", // Ongoing (Today)
    isPublic: true,
    description: "Competitive 5-a-side football match in GRA.",
    attendees: 18,
    isFree: true,
    participantImages: AVATARS.slice(0, 3),
  },
  {
    id: 3,
    lat: 4.818,
    lng: 7.04,
    emoji: "🍻",
    title: "Neighborhood Drinks Night",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1519671482749-fd09be7ccebf"),
    status: "past",
    date: "2026-04-01",
    isPublic: true,
    description: "Relax with neighbors over local drinks.",
    attendees: 42,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 4,
    lat: 4.8175,
    lng: 7.036,
    emoji: "🏠",
    title: "House Party Vibes",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1590080870058-b7d3c8c1ff70"),
    status: "upcoming",
    date: "2026-04-20",
    isPublic: false, // Private event
    description: "Chill house party with music and snacks.",
    attendees: 25,
    isFree: true,
    participantImages: AVATARS.slice(0, 4),
  },
  {
    id: 5,
    lat: 4.821,
    lng: 7.039,
    emoji: "🎮",
    title: "Gaming Meetup GRA",
    category: "entertainment",
    image: opt("https://images.unsplash.com/photo-1603791440384-56cd371ee9a7"),
    status: "ongoing",
    date: "2026-04-08",
    isPublic: true,
    description: "Compete in FIFA or Call of Duty.",
    attendees: 30,
    isFree: false,
    price: "₦2,000",
    participantImages: AVATARS,
  },
  {
    id: 6,
    lat: 4.876,
    lng: 7.058,
    emoji: "🏀",
    title: "Basketball Ada George",
    category: "sports",
    image: opt("https://images.unsplash.com/photo-1517649763962-0c623066013b"),
    status: "upcoming",
    date: "2026-04-12",
    isPublic: true,
    description: "Friendly basketball match in Ada George.",
    attendees: 22,
    isFree: true,
    participantImages: AVATARS.slice(0, 2),
  },
  {
    id: 7,
    lat: 4.878,
    lng: 7.055,
    emoji: "🎶",
    title: "Live Band Night Ada George",
    category: "entertainment",
    image: opt("https://images.unsplash.com/photo-1524230572916-58a7b80b4f37"),
    status: "ongoing",
    date: "2026-04-08",
    isPublic: true,
    description: "Live music from local bands.",
    attendees: 65,
    isFree: false,
    price: "₦3,000",
    participantImages: AVATARS,
  },
  {
    id: 8,
    lat: 4.875,
    lng: 7.06,
    emoji: "🏐",
    title: "Beach Volleyball Meetup",
    category: "sports",
    image: opt("https://images.unsplash.com/photo-1505842465776-3e3e8d7b8e0f"),
    status: "upcoming",
    date: "2026-04-25",
    isPublic: true,
    description: "Sun, sand, and volleyball in Bonny.",
    attendees: 15,
    isFree: true,
    participantImages: AVATARS.slice(0, 3),
  },
  {
    id: 9,
    lat: 4.874,
    lng: 7.057,
    emoji: "🕺",
    title: "TikTok Dance Challenge",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1607746882042-944635dfe10e"),
    status: "upcoming",
    date: "2026-04-18",
    isPublic: true,
    description: "Show off your moves!",
    attendees: 150,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 10,
    lat: 4.84,
    lng: 7.055,
    emoji: "🎨",
    title: "Street Art Walk Odili",
    category: "wellness",
    image: opt("https://images.unsplash.com/photo-1506015391300-4802dc78b78e"),
    status: "upcoming",
    date: "2026-04-22",
    isPublic: true,
    description: "Explore Odili Road's street art.",
    attendees: 34,
    isFree: true,
    participantImages: AVATARS.slice(0, 4),
  },
  {
    id: 11,
    lat: 4.845,
    lng: 7.045,
    emoji: "🎶",
    title: "Jazz Night Bonny",
    category: "entertainment",
    image: opt("https://images.unsplash.com/photo-1518972559570-7cc1309ea09b"),
    status: "past",
    date: "2026-03-30",
    isPublic: true,
    description: "Live jazz music in Bonny.",
    attendees: 28,
    isFree: false,
    price: "₦10,000",
    participantImages: AVATARS,
  },
  {
    id: 12,
    lat: 4.86,
    lng: 7.05,
    emoji: "🎤",
    title: "Open Mic Night Riverside",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4"),
    status: "upcoming",
    date: "2026-04-14",
    isPublic: true,
    description: "Music, poetry, or comedy.",
    attendees: 45,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 13,
    lat: 4.855,
    lng: 7.04,
    emoji: "🏃",
    title: "Sunrise Fun Run",
    category: "wellness",
    image: opt("https://images.unsplash.com/photo-1558611848-73f7eb4001a1"),
    status: "ongoing",
    date: "2026-04-08",
    isPublic: true,
    description: "Refreshing community morning run.",
    attendees: 80,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 14,
    lat: 4.85,
    lng: 7.035,
    emoji: "🍺",
    title: "Local Brewery Tasting",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1510936111840-dc87aebf7b6c"),
    status: "past",
    date: "2026-03-25",
    isPublic: true,
    description: "Taste authentic local brews.",
    attendees: 12,
    isFree: false,
    price: "₦4,500",
    participantImages: AVATARS.slice(0, 3),
  },
  {
    id: 15,
    lat: 4.848,
    lng: 7.042,
    emoji: "🎸",
    title: "Indie Band Showcase",
    category: "entertainment",
    image: opt("https://images.unsplash.com/photo-1524230572916-58a7b80b4f37"),
    status: "upcoming",
    date: "2026-04-30",
    isPublic: true,
    description: "Discover the best local indie bands.",
    attendees: 95,
    isFree: false,
    price: "₦2,500",
    participantImages: AVATARS,
  },
  {
    id: 16,
    lat: 4.845,
    lng: 7.038,
    emoji: "🛍️",
    title: "Weekend Market Fair",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1505842465776-3e3e8d7b8e0f"),
    status: "upcoming",
    date: "2026-04-11",
    isPublic: true,
    description: "Handmade crafts, food, and music.",
    attendees: 210,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 17,
    lat: 4.84,
    lng: 7.03,
    emoji: "🎨",
    title: "Art & Crafts Expo",
    category: "education",
    image: opt("https://images.unsplash.com/photo-1495435229349-e86db7bfa013"),
    status: "ongoing",
    date: "2026-04-08",
    isPublic: true,
    description: "Unique arts from local creators.",
    attendees: 55,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 18,
    lat: 4.835,
    lng: 7.025,
    emoji: "🎶",
    title: "Acoustic Night GRA",
    category: "entertainment",
    image: opt("https://images.unsplash.com/photo-1518972559570-7cc1309ea09b"),
    status: "past",
    date: "2026-03-20",
    isPublic: true,
    description: "Acoustic performances in a cozy setting.",
    attendees: 30,
    isFree: false,
    price: "₦5,000",
    participantImages: AVATARS.slice(0, 4),
  },
  {
    id: 19,
    lat: 4.83,
    lng: 7.02,
    emoji: "🎤",
    title: "Comedy Night Riverside",
    category: "entertainment",
    image: opt("https://images.unsplash.com/photo-1529333166437-7750a6dd5a70"),
    status: "upcoming",
    date: "2026-04-19",
    isPublic: true,
    description: "Laugh with local comedians.",
    attendees: 110,
    isFree: false,
    price: "₦3,500",
    participantImages: AVATARS,
  },
  {
    id: 20,
    lat: 4.825,
    lng: 7.015,
    emoji: "🍲",
    title: "Street Food Crawl",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1551782450-a2132b4ba21d"),
    status: "ongoing",
    date: "2026-04-08",
    isPublic: true,
    description: "Taste local street food across the city.",
    attendees: 180,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 21,
    lat: 4.82,
    lng: 7.01,
    emoji: "⚽",
    title: "Local Soccer Match",
    category: "sports",
    image: opt("https://images.unsplash.com/photo-1517649763962-0c623066013b"),
    status: "past",
    date: "2026-03-15",
    isPublic: true,
    description: "Amateur soccer teams in action.",
    attendees: 300,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 22,
    lat: 4.815,
    lng: 7.005,
    emoji: "🎤",
    title: "Karaoke Night",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1520085179755-2baf046c4a6b"),
    status: "upcoming",
    date: "2026-04-10",
    isPublic: true,
    description: "Sing your heart out with friends.",
    attendees: 40,
    isFree: true,
    participantImages: AVATARS.slice(0, 3),
  },
  {
    id: 23,
    lat: 4.81,
    lng: 7.0,
    emoji: "🏃",
    title: "Charity Fun Run",
    category: "wellness",
    image: opt("https://images.unsplash.com/photo-1526404188837-52aa8314b7cf"),
    status: "upcoming",
    date: "2026-05-01",
    isPublic: true,
    description: "Run for a cause.",
    attendees: 500,
    isFree: false,
    price: "Donation",
    participantImages: AVATARS,
  },
  {
    id: 24,
    lat: 4.805,
    lng: 6.995,
    emoji: "🎨",
    title: "Gallery Opening PH",
    category: "education",
    image: opt("https://images.unsplash.com/photo-1491333078588-55b6733c7de6"),
    status: "ongoing",
    date: "2026-04-08",
    isPublic: true,
    description: "New gallery featuring contemporary artists.",
    attendees: 60,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 25,
    lat: 4.8,
    lng: 6.99,
    emoji: "🎬",
    title: "Film Screening PH",
    category: "entertainment",
    image: opt("https://images.unsplash.com/photo-1496116218416-1d5c15d1d66c"),
    status: "past",
    date: "2026-04-05",
    isPublic: true,
    description: "Independent films by Nigerian filmmakers.",
    attendees: 45,
    isFree: false,
    price: "₦1,500",
    participantImages: AVATARS.slice(0, 4),
  },
  {
    id: 26,
    lat: 4.795,
    lng: 6.985,
    emoji: "🎶",
    title: "Afropop Dance Party",
    category: "entertainment",
    image: opt("https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4"),
    status: "upcoming",
    date: "2026-04-28",
    isPublic: true,
    description: "Dance to the hottest Afropop tracks.",
    attendees: 220,
    isFree: false,
    price: "₦4,000",
    participantImages: AVATARS,
  },
  {
    id: 27,
    lat: 4.79,
    lng: 6.98,
    emoji: "🍹",
    title: "Cocktail Night PH",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1526040652367-28f1e35f83a1"),
    status: "ongoing",
    date: "2026-04-08",
    isPublic: true,
    description: "Creative cocktails and live music.",
    attendees: 75,
    isFree: false,
    price: "₦8,000",
    participantImages: AVATARS,
  },
  {
    id: 28,
    lat: 4.785,
    lng: 6.975,
    emoji: "🎤",
    title: "Poetry Slam",
    category: "social",
    image: opt("https://images.unsplash.com/photo-1493149738420-3e4e74d3d19b"),
    status: "past",
    date: "2026-03-10",
    isPublic: true,
    description: "Powerful spoken word performances.",
    attendees: 55,
    isFree: true,
    participantImages: AVATARS.slice(0, 3),
  },
  {
    id: 29,
    lat: 4.78,
    lng: 6.97,
    emoji: "🎨",
    title: "Street Art Walk",
    category: "wellness",
    image: opt("https://images.unsplash.com/photo-1506015391300-4802dc78b78e"),
    status: "upcoming",
    date: "2026-04-29",
    isPublic: true,
    description: "Guided walk exploring murals.",
    attendees: 30,
    isFree: true,
    participantImages: AVATARS,
  },
  {
    id: 30,
    lat: 4.775,
    lng: 6.965,
    emoji: "🏃",
    title: "Sunset Yoga",
    category: "wellness",
    image: opt("https://images.unsplash.com/photo-1526404188837-52aa8314b7cf"),
    status: "ongoing",
    date: "2026-04-08",
    isPublic: true,
    description: "Relaxing sunset yoga session.",
    attendees: 20,
    isFree: true,
    participantImages: AVATARS.slice(0, 2),
  },
];
